spring.application.name=ai-grievance-system

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alonewarrior123456@gmail.com
spring.mail.password=wpce mazd svlf jpoc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# JWT Configuration
# ===============================
jwt.secret=MyComplaintSystemSecretKeyForJwtAuthentication2026SecureKey123456
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB